caila:
  accessToken: c5c638a4-60ec-49c1-83ae-2e2325ed00e4
  confidenceThreshold: 0.3

connection:
  mode: polling
  accessToken: c5c638a4-60ec-49c1-83ae-2e2325ed00e4

bot:
  onErrorReply: "Извините, у нас все сломалось"